# Generated by Django 4.1.1 on 2023-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(default='none', upload_to='posts/'),
        ),
    ]
