# Generated by Django 4.1.1 on 2023-03-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_posts_likes_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
