# Generated by Django 4.1.1 on 2023-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_usr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usr',
        ),
    ]
