# Generated by Django 4.1.1 on 2023-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsys', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='rawbody',
            field=models.TextField(blank=True, default=''),
        ),
    ]
