# Generated by Django 4.1.1 on 2022-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Images', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Content', models.TextField(blank=True)),
            ],
        ),
    ]
