# Generated by Django 4.1.1 on 2022-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywikiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
