# Generated by Django 4.1.1 on 2022-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywikiapp', '0002_alter_newentry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='textdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='Title',
        ),
    ]
