# Generated by Django 4.1.1 on 2022-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywikiapp', '0004_alter_textdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='Upload_Images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
