# Generated by Django 4.1.1 on 2022-10-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='Posted_By',
        ),
    ]
