# Generated by Django 4.1.1 on 2022-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_listings_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
