# Generated by Django 4.1.1 on 2022-10-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_listings_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='comment',
        ),
        migrations.AddField(
            model_name='bid',
            name='auc_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction_listings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='auc_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auction.auction_listings'),
        ),
    ]
