# Generated by Django 4.1.1 on 2022-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_auction_listings_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Bid_Added_By',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='Comment_Added_By',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
