# Generated by Django 4.1.1 on 2022-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_bid_bid_added_by_comments_comment_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=24)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Price', models.BigIntegerField(null=True)),
                ('Display_Image', models.TextField(null=True)),
            ],
        ),
    ]
