# Generated by Django 4.1.1 on 2022-10-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_notification_notified_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notified_user',
            new_name='Notified_User',
        ),
    ]
