# Generated by Django 4.1.1 on 2022-10-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_rename_notified_user_notification_notified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Status',
            field=models.TextField(null=True),
        ),
    ]
