# Generated by Django 4.1.1 on 2022-10-09 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Notified_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notific', to=settings.AUTH_USER_MODEL),
        ),
    ]
