# Generated by Django 4.1.1 on 2022-10-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_notification_notified_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
