# Generated by Django 4.1.1 on 2023-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsys', '0003_email_rawbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
